### ISSUE TITLE
Can we have onInput event ? because onChange is depricated in IE

### ISSUE THREAD

**Issue by akashishu777** [nkbt/react-debounce-input#108]
```
 <DebounceInput
          minLength={2}
          debounceTimeout={300}
          onChange={event => this.setState({value: event.target.value})} />
```

Can we have onInput?

**Comment by akashishu777** [comment]
I am not saying onChange is deprecated in react, I am saying Internet Explorer v11 doesn't support the onChange event.

React does not have the behavior of default 'onChange' event. The 'onChange' which we see in react has the behavior of default 'onInput' event.

**Comment by nkbt** [comment]
This is a react component, so whatever comes to the DOM is controlled by React. There is no sense to change API from onChange to onInput, since onChange is not deprecated in React.
