### ISSUE TITLE
React 17.x support please

### ISSUE THREAD

**Issue by cgmack** [nkbt/react-debounce-input#137]
When installing react-debounce-input in my react 17.0.1 project, I get the following error. It appears that react-debounce-input@3.2.3 is limited to `react@"^15.3.0 || ^16.0.0"`. Is there something preventing 17.x support? Is there a timeline for this support? Thank you. 

```
$ npm i --save react-debounce-input
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: frontend@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.3.0 || ^16.0.0" from react-debounce-input@3.2.3
npm ERR! node_modules/react-debounce-input
npm ERR!   react-debounce-input@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by nkbt** [comment]
It should work with any modern React version. Just need to add 17 to peer deps

Meanwhile you can use `--force, or --legacy-peer-deps` to get it installed.

**Comment by cgmack** [comment]
Great. Thanks for confirming.

**Comment by Berend-Kalberg** [comment]
Second this. Has not been fixed yet. Came here to confirm if it still works because its a great tool.

**Comment by iMoses-Apiiro** [comment]
> It should work with any modern React version. Just need to add 17 to peer deps

Can you please add it and push a new patch version?

**Comment by jschaffer-edr** [comment]
Added PR https://github.com/nkbt/react-debounce-input/pull/142

**Comment by char0n** [comment]
Cool, any ETA for a release?

**Comment by nkbt** [comment]
<img width="519" alt="Screen Shot 2021-07-20 at 12 09 54" src="https://user-images.githubusercontent.com/175264/126251708-7b215eb9-b961-42bd-ade0-fd1a00330e48.png">
