### ISSUE TITLE
react-native support

### ISSUE THREAD

**Issue by vtaits** [nkbt/react-debounce-input#148]
`TextInput` of `react-native` has a different event in `onChange`

https://reactnative.dev/docs/textinput#onchange

Also it uses `onKeyPress` instead of `onKeyDown`

https://reactnative.dev/docs/textinput#onkeypress

Looks like needs to add new props:

- `getTextFromEvent`
- `keyDownHandlerName`
- `checkIsEnterKey`

**Comment by nkbt** [comment]
I am not working with react native
Definitely not going to add more props to this component 💯
I suggest forking and updating for react native specifically. There is no sense making component more complex if you can just copy it and update for your usecase
