### ISSUE TITLE
Add support for loading state to custom Input component

### ISSUE THREAD

**Issue by Nithur-M** [nkbt/react-debounce-input#152]
I want to display the loading state inside my custom Input component. 
It'd be helpful if you can add support for passing loading state.

**Comment by nkbt** [comment]
Loading state is not a concern of an input. It can be solved by wrapping input and adding loading ui + props to that new component. That is a specific app concern

**Comment by Nithur-M** [comment]
> Loading state is not a concern of an input. It can be solved by wrapping input and adding loading ui + props to that new component. That is a specific app concern

When I pass props to the component it throws an unsupported type error. (error: expected string but got an object).
Is it possible to send props to the custom component by any other means?

**Comment by nkbt** [comment]
I have no idea what you are doing.

**Comment by Nithur-M** [comment]
I couldn't pass any props as follows:
`<DebounceInput
        minLength={3}
        debounceTimeout={300}
        element={CustomInput(props)}
        onChange={changeHandler}
      />`
It throws the above mentioned error. How am I supposed to pass the loading state to my `customInput`?
Thank you.

**Comment by nkbt** [comment]
Arbitrary props will be passed through to the input element
https://github.com/nkbt/react-debounce-input#arbitrary-props-will-be-transferred-to-rendered-input

**Comment by Nithur-M** [comment]
Thank you so much.
