### ISSUE TITLE
Problem with onBlur

### ISSUE THREAD

**Issue by johnkucharsky** [nkbt/react-debounce-input#157]
onBlur triggers on mount

**Comment by nkbt** [comment]
Please submit code sandbox with the issue

**Comment by johnkucharsky** [comment]
When i created codesandbox everything worked. The problem was with autofocus. I don't know why it works in codesandbox, but doesn't work in my component(mui drawer). I want to focus on input when drawer opens

**Comment by nkbt** [comment]
How do you think I could help if it is not possible to reproduce outside of your own app?

**Comment by johnkucharsky** [comment]
Of course it's not possible

**Comment by JohnKucharsky** [comment]
Everything works good
