### ISSUE TITLE
clear input programmatically

### ISSUE THREAD

**Issue by Artem-Schander** [nkbt/react-debounce-input#18]
I'm trying to clear the input from my search input by hitting a button, but the only solution i found seems a little hacky :(

    clear() {
      this.refs.search.getDOMNode().value = '';
    }

besides the fact that it is a ugly peace of code, i'm getting a warning:

    Warning: DebounceInput.getDOMNode(...) is deprecated. Please use ReactDOM.findDOMNode(instance) instead.

I think I'm overseeing something (its late here). Is there a better way doing this?

**Comment by nkbt** [comment]
Hi @Artem-Schander, just set `value=""` to `DebouncedInput` =)

**Comment by Artem-Schander** [comment]
cool, thanks. I'll try later :)

**Comment by Artem-Schander** [comment]
I have a little delay. I think it's because of the state change time (redux -> dispatch).
However, It works :)

Keep up the good work.

**Comment by nkbt** [comment]
Thanks!
