### ISSUE TITLE
onFocus & onBlur props

### ISSUE THREAD

**Issue by timbofield** [nkbt/react-debounce-input#19]
Hi 
Thanks for you work on this.

I need listen for on focus and on blur, does DebounceInput swallow these ? Any way to achieve this ? 

     <DebounceInput
          className="c-search__input input-group-field"
          minLength={3}
          name="site-search"
          id="site-search"
          placeholder="Search..."
          aria-label="Search..."
          onChange={this._handleSearchChange}
          onFocus={this._handleSearchFocus}
          onBlur={this._handleSearchBlur} />

**Comment by timbofield** [comment]
My mistake I can see your code is handling this correctly already in the source.

**Comment by nkbt** [comment]
Too easy, Tim :)
