### ISSUE TITLE
React 15 support

### ISSUE THREAD

**Issue by amertak** [nkbt/react-debounce-input#20]
Would it be possible to try add peer dependency also for v15. I could test it out.

**Comment by tomdcc** [comment]
+1

**Comment by nkbt** [comment]
Oh dear, how have I missed this, thanks for a reminder, @tomdcc

**Comment by nkbt** [comment]
`+ react-debounce-input@2.3.0`

**Comment by tomdcc** [comment]
Thanks Nik!

**Comment by amertak** [comment]
Thanks :)

**Comment by nkbt** [comment]
👌
