### ISSUE TITLE
Doesn't seem to work.

### ISSUE THREAD

**Issue by pjebs** [nkbt/react-debounce-input#27]
My old function looked like this:

```
onChange={this.couponChanged}
```

Using your component I tried this:

```
onChange={event => this.couponChanged()}
```
It didn't work. I don't think event gets passed through.

```
couponChanged: function(e) {
		e.preventDefault()
		this.props.update(e.target.value);
		this.setState({coupon_code: e.target.value});
	},
```

**Comment by nkbt** [comment]
Hi. Try onChange={event => this.couponChanged(event)}

**Comment by pjebs** [comment]
I don't think it worked either.

**Comment by nkbt** [comment]
Also if you then update value from outside "recursively" then it may not
work too

See react-text-filter as an example of debounce-input wrapper that passes
values through properly

**Comment by pjebs** [comment]
Thanks for your help. I really appreciate it.
