### ISSUE TITLE
onChange firing when it shouldn't be

### ISSUE THREAD

**Issue by gkrinc** [nkbt/react-debounce-input#35]
I have the DebounceInput component loaded beside a few other components that have events and call actions.

When my page loads and I click one of my component the onChange handler in the DebounceInput DOES NOT fire which I expect. If I type in the DebounceInput to trigger the onChange handler it DOES fire as expected. Now, if I click my component again the first thing to happen before any actions are triggered is the onChange handler for the DebounceInput...this doesn't make any sense. The DebounceInput onChange fires before the onClick of my component, which is the action I'm taking, how/why is this happening?

**Comment by gkrinc** [comment]
forceNotifyOnBlur was the "problem". I set it to false and all is good

**Comment by nkbt** [comment]
Cheers! Happy it's solved!
