### ISSUE TITLE
Weird Edge-Casey Render Race

### ISSUE THREAD

**Issue by ericf89** [nkbt/react-debounce-input#40]
I feel like I'm probably running into some issues that are specific to my particular use case.  I ended up forking and fixing them [here](https://github.com/nkbt/react-debounce-input/compare/master...ericf89:master), but it probably is too specific to my case to be merged in.  Thought I'd let you look it over though just in case. 😄 

I have a situation where my debounced input is re-rendered (by a component higher up the tree) while it's debouncing its onChange handler.   This means it receives props, sets state, and renders with it's `props` value which is normally a couple keystrokes behind the user, before triggering it's change handler that properly updates the value of the input in the store, which trickles all the way back down again. 

The result is a kinda flicker back and forth between the correct value and the one in props as everything stabilizes.  

I 'fixed' it by keeping track of whether or not the debounced input is currently `debouncing`. If so, it ignores `value` changes in its props, (under the assumption that it'll change again when the debounced handler actually fires/notifies.  I don't really like ignoring the props change...  but it seemed like the simplest way to fix my issue. 💀 

Let me know if you think this is actually useful, and I can formalize it into a PR, or you can cannibalize it how you see fit. 

If not you can close this, and I'll use my version for my use case.   Cheers!

**Comment by nkbt** [comment]
Thanks for sharing!
I think it is possible...  Though I would rather use `this.isDebouncing` instead of state. And also it makes sense to check if debounce has any notion of if it is now debouncing something.

**Comment by ericf89** [comment]
Good point! Don't know what I was thinking with the `state`.

I looked through the [lodash docs](https://lodash.com/docs#debounce) and don't see any api for determining the debounce state, but I'll investigate this a little more, clean it up, and send over a PR.

**Comment by nkbt** [comment]
Thanks, really appreciate it

**Comment by nkbt** [comment]
Nice catch with  this.notify.flush();

**Comment by scandinaro** [comment]
@ericf89 I'm having this same issue.  Do you have a fork I can use with your fix?

**Comment by ericf89** [comment]
Hey @scandinaro, sorry for the delay.  I remember installing [this commit]( https://github.com/ericf89/react-debounce-input/commit/48b497dcfe595fb7c915b6909c1465a15a257904) for a while and I think it worked ok.  [The branch](https://github.com/ericf89/react-debounce-input/tree/ef_preventing_double_notify_on_blur_and_debounce) is little behind the current master though, so you may be missing other useful things though.  Hope it helps!

**Comment by nkbt** [comment]
Published react-debounce-input@2.4.2
