### ISSUE TITLE
Trouble with ReactComponent as element prop

### ISSUE THREAD

**Issue by gkrinc** [nkbt/react-debounce-input#48]
I'm having trouble with setting the element prop to a custom react component. My component has an onChange prop and value prop, but I get this error when using it as the element prop of DebounceInput:

`invariant.js:38Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of 'DebounceInput'.`

Am I configuring DebounceInput incorrectly? Am I supposed to set the value and onChange props on MyTextField?

```
let searchBox = <MyTextField hint={searchPlaceholder}
                                        style={{padding:'0px 0px'}}
                                        iconStyle={{padding:'8px 0px'}} />;

<DebounceInput
                                minLength={2}
                                debounceTimeout={400}
                                onChange={(event) => this.props.executeSearch(event.target.value)}
                                placeholder={searchPlaceholder}
                                forceNotifyOnBlur={false}
                                value={query}
                                element={searchBox}   />
```

**Comment by gkrinc** [comment]
Ok it seems like I am doing something wrong. If I do this instead it sort of works:

```
import MyTextField from './MyTextField';

<DebounceInput
                                minLength={2}
                                debounceTimeout={400}
                                onChange={(event) => this.props.executeSearch(event.target.value)}
                                placeholder={searchPlaceholder}
                                forceNotifyOnBlur={false}
                                value={query}
                                element={MyTextField}   />
```
I think the only problem now is my custom text field have it's own UI state and only triggers an action to update store state onBlur.

**Comment by nkbt** [comment]
Yep you cannot pass react element, but inly react Component (or one of
default tags as strings).

If you pass custom component, make sure it supports onChange prop callback,
and onBlur.

Other than that, debounce does not care of your component internals. Check
the source code for more details

Cheers!

**Comment by Nithur-M** [comment]
> Yep you cannot pass react element, but inly react Component (or one of default tags as strings).
> 
> If you pass custom component, make sure it supports onChange prop callback, and onBlur.
> 
> Other than that, debounce does not care of your component internals. Check the source code for more details
> 
> Cheers!

Should I add the onchange handler in my component?

**Comment by nkbt** [comment]
> Should I add the onchange handler in my component?

Yes you certainly should use `onChange`

From README https://github.com/nkbt/react-debounce-input#usage:

```js
import React from 'react';
import ReactDOM from 'react-dom';
import {DebounceInput} from 'react-debounce-input';

class App extends React.Component {
  state = {
    value: ''
  };

  render() {
    return (
      <div>
        <DebounceInput
          minLength={2}
          debounceTimeout={300}
          onChange={event => this.setState({value: event.target.value})} />

        <p>Value: {this.state.value}</p>
      </div>
    );
  }
}

const appRoot = document.createElement('div');
document.body.appendChild(appRoot);
ReactDOM.render(<App />, appRoot);
```

**Comment by Nithur-M** [comment]
I am passing a custom react component to the element property. 
Thanks. I figured out it is available via props.
