### ISSUE TITLE
Create Core component that will work with any kind of input

### ISSUE THREAD

**Issue by nkbt** [nkbt/react-debounce-input#5]
With Select, or Textarea or anything else. And re-use it in Input component itself.

**Comment by ronanwize** [comment]
Love this component. Please do your best to keep it simple, we're trying to keep our bundle size down :D

**Comment by Data-Meister** [comment]
In React <textarea /> has identical behavior to <input /> so it makes sense to provide this as an option. I have submitted a pull request.
