### ISSUE TITLE
Cannot set key prop on input field

### ISSUE THREAD

**Issue by mkapnick** [nkbt/react-debounce-input#52]
Would be nice to be able to set a `key` prop on the component. This is advantageous on certain kinds of re renders.

**Comment by mkapnick** [comment]
I can make a PR on this

**Comment by nkbt** [comment]
`key` is internal React-specific prop. It is not possible to pass it through. If you use DebounceInput in a `map` or something, add `key` to it and React will take care of re-renders.

```js
<DebounceInput key={name} name={name} />
```

 would perfectly work.

**Comment by nkbt** [comment]
https://facebook.github.io/react/docs/multiple-components.html

> The `key` should *always* be supplied directly to the components in the array, not to the container HTML child of each component in the array

**Comment by mkapnick** [comment]
I would like the key to be set on the `input` element, which is wrapped by `DebounceInput`. So whether it's called `key` or `id` doesn't matter, as long as the `input` element is set as `<input key='some-id'></input>`. I'm not able to set the key element on the input field AFAIK

**Comment by nkbt** [comment]
It is just impossible in React. It strips key prop away. Check the doc :)
