### ISSUE TITLE
event.persist is not a function

### ISSUE THREAD

**Issue by ddcech** [nkbt/react-debounce-input#56]
I have a custom input component that just passes a value and not an event.
For example the [rc-slider](https://github.com/react-component/slider) component just returns a value on the onChange.

Looking through the react debounce input code, I can see that `event.persist()` is being called in the onChange function. Maybe we can check for an event before the `event.persist()`.

**Comment by nkbt** [comment]
Debounce input is supposed to be compatible drop-in replacement for normal input. If you want to use it with some other custom input, then it should be compatible with react input too. So you need to pass event to `onChange` not a value.

Thanks for suggestion, but I think that patching over library component for non-standard behavior custom component is not really a good idea.
