### ISSUE TITLE
onChange Fired When I Exit Input

### ISSUE THREAD

**Issue by realph** [nkbt/react-debounce-input#60]
When I type inside my input field the `onChange` event is firing correctly, however when I click outside of the input field it also fires the `onChange` event.

![onchange](https://cloud.githubusercontent.com/assets/2334951/20650046/4c2b3d8e-b4c5-11e6-9b68-1bc522938a7d.gif)

My code looks like this:

    search(query) {
      console.log('onChange fired');
    }

    render() {
      return (
        <DebounceInput minLength={2}
                        debounceTimeout={300}
                        onChange={ this.search }
                        placeholder="Search..." />
      );
    }

Any idea why this might be happening? I had a look at the [CodePen example](http://codepen.io/nkbt/pen/VvmzLQ) and it doesn't seem to fire when clicking outside of the input.

Any help is appreciated. Thanks in advance!

**Comment by nkbt** [comment]
Oh that is intended behaviour. There is a flag (defaults to `true`) for this. https://github.com/nkbt/react-debounce-input#forcenotifyonblur-proptypesbool-default-true

**Comment by realph** [comment]
@nkbt Missed this option. Thanks!
