### ISSUE TITLE
putting focus on a DebounceInput

### ISSUE THREAD

**Issue by Pomax** [nkbt/react-debounce-input#65]
Heya, we're using DebounceInput in a project at the moment where we need to ensure that certain user interactions focus the input element wrapped by DebounceInput - I don't see a `focus()` function exposed in your README, is there one? If not, can one be added?

(Specifically we were hoping to be able to just give the DebounceInput a `ref` attribute and then call something like `this.refs.debouncedSearch.focus()`)

**Comment by nkbt** [comment]
It passes all props down to the input, so you can use any prop. It is mentioned in the readme

**Comment by Pomax** [comment]
I.. don't understand, that doesn't answer the question *at all*. `.focus()` is a JS API function found on the HTMLElement prototype, which gets blocked off by DebounceInput because it does *not* do any clever rebinding that allows you to call `debounceElement.focus()` and have it focus the input element.

This question has *nothing* to do with props, it's about the other direction: debounce wraps an input, how do I get to that input element so I can call its normal JS API functions like `.focus()` etc?

**Comment by nkbt** [comment]
Sorry, I missed the point of you trying to access HTML stuff...

I reckon I need to add `inputRef` prop (since `ref` would be applied to Debounce wrapper).

**Comment by Pomax** [comment]
https://facebook.github.io/react/docs/refs-and-the-dom.html#adding-a-ref-to-a-dom-element actually covers this pretty explicitly for `focus()`, so it might be enough to just add a few functions on a "by request" basis. Alternatively, it might be worth adding a public API function like `getTextInput()` to the DebounceInput so that no matter what people put in, calling `debouncer.getTextInput()` yields the input/textarea that is used by the DebounceInput.

It appears that string refs are [on their way out](https://facebook.github.io/react/docs/refs-and-the-dom.html#legacy-api-string-refs) but ref callbacks will still work so you could do something like:

```
class DebounceInput extends Component {
  constructor() {
    this.inputelement = false;
  }
  getTextInput() {
    return this.inputelement;
  }
  render() {
    var textinput, opts = {
      ref: e => (this.inputelement = e),
      className: ...,
      ...
    };
    if (...) {
      textinput = <input {...opts} />
    } else {
      textinput = <textarea {...opts} />
    }
    ...
    return textinput;
  }
```

**Comment by oyeanuj** [comment]
@nkbt  As we debate string refs vs ref callbacks, also thought I'd bring the other issue into discussion here as well - https://github.com/moroshko/react-autosuggest/issues/169#issuecomment-271135637

PS.  I have still been meaning to PR that, but hadn't had a chance yet. Sorry about that :(

**Comment by shawnbissell** [comment]
I vote for option 1 
`<DebounceInput inputRef={...} />`
since its the "[React supported](https://facebook.github.io/react/docs/refs-and-the-dom.html#exposing-dom-refs-to-parent-components)" way and other libraries such as [React Bootstrap](https://react-bootstrap.github.io/components.html#forms-props-form-control) work that way.

**Comment by serjebulavsky** [comment]
@nkbt Hello, faced the same problem. Is it fixed currently ?

**Comment by nkbt** [comment]
Published new version, updated codepen example https://codepen.io/nkbt/pen/VvmzLQ?editors=0010
