### ISSUE TITLE
bower install not working

### ISSUE THREAD

**Issue by K3CK** [nkbt/react-debounce-input#69]
Running bower install like featured in the docs returns:

`bower bower#*                    EHTTP Status code of 404`

Obviously coming from an invalid URL: 
https://unpkg.com/react-debounce-input/bower.zip 
which redirects to 
https://unpkg.com/react-debounce-input@3.0.0/bower.zip

**Comment by nkbt** [comment]
Hm that's odd. To be fair I would like to drop bower support at all.

For now and later you can use full path to js file on unpkg (same as in old
good script tag way in docs) and it should just work fine... the only thing
it does not do - no automatic dependencies resolution

-- 
Nik Butenko
nik@butenko.me
http://github.com/nkbt

**Comment by K3CK** [comment]
Yes, go ahead with dropping bower support. 
Managed to install by using npm. Thanks!

**Comment by nkbt** [comment]
Great. Good news (for maintainers) - Bower is deprecated anyway now.
