### ISSUE TITLE
Add option to send event to onChange

### ISSUE THREAD

**Issue by cbrwizard** [nkbt/react-debounce-input#9]
Hey, good component.
But can you add an option so that during onChange an event is being sent, not just plain value? Sometimes I need to send the input key to my handleChange function and I want to take it from an event object with event.target.name. Or perhaps send it as a second argument.

**Comment by nkbt** [comment]
Yeah, I was thinking about that too. Seems like it would be better to have debounced input act as it is normal input.

**Comment by nkbt** [comment]
I've just realized why I did not pass full event to onChange. Debounced onChange is invoked after some delay. Which means original `event`'s references may not be valid anymore (added #38).

I mean, event is a mutable object and after some timeout many props of original event become a bit different to what they were originally set to.

I am going to dig it a bit more, though it would be more convenient if event is passed through anyway.

**Comment by cbrwizard** [comment]
Yeah, thanks man! Now no need to write a separate handler for this input :+1:
