### ISSUE TITLE
Advantages over lodash debounce?

### ISSUE THREAD

**Issue by waynebloss** [nkbt/react-debounce-input#92]
When I searched for `react debounce input` I found this library of course, but I also found articles, tutorials and other resources that implemented the "debounce input onChange" logic using lodash debounce or something just like it. [Here is probably the simplest example, on jsFiddle](https://jsfiddle.net/petewailes/kp04015o/).

So, after looking through the source code of `react-debounce-input`, I see that it's doing things very differently and there is a lot more code than I expected. Can anyone tell me what is the advantage of using `react-debounce-input` for the simple case where you need to debounce calls from `onChange` to `setState`?

Here are the advantages of `react-debounce-input` that I can see:

1. It's a component, so nicer to use than pulling lodash debounce in and applying it everywhere.
2. You have conditional notifications with `minLength`, `forceNotifyEnter` and `forceNotifyBlur`.

I'm guessing that `2.` is the reason that the code is so different than the simple jsFiddle example that I linked to. However, if you don't really need `2.` and you don't care about `1.` because you can just make your own component...is there any reason to not just do that?

**Comment by nkbt** [comment]
> because you can just make your own component...is there any reason to not just do that?

No reason. Just create your own component. It will be the same (or slightly different) as `ReactDebounceInput`.

Also don't forget about some edge cases, like canceling debounce when component is unmounted, etc.

And yeah, you can apply the same logic for every single library on NPM. You indeed don't have to use it and write each one yourself.

**Comment by waynebloss** [comment]
Thanks for your response.

> canceling debounce when component is unmounted...

I'm not sure why I would want to throw away user input, but edge cases are exactly the kind of thing I'm interested in hearing about.

I would never cancel the debounce in my implementation. Could you say why you need to do that and is it done at all times or conditionally by `react-debounce-input`?

**Comment by waynebloss** [comment]
OK, actually I see what you are doing now - you're not throwing away the user input you're just sending the notification before the component is unmounted. I could see where that might happen, but I don't think I'll need that either.

**Comment by waynebloss** [comment]
I'll add these to the list of advantages for `react-debounce-input`:

* Throwing out updates from props when `this.isDebouncing` is true is a nice performance enhancement.
* You already cover any edge cases to make sure that user input is always delivered.

After perusing the source instead of just skimming it like I did the first time, I can see that this is a good component and now fully understand the source enough to say that I will probably use it instead of making my own. I didn't mean to waste your time but this information wasn't jumping out at me from the README. 

Thanks for your code!

**Comment by nkbt** [comment]
Debounce is a side-effect and any component with side-effect has to make sure there are no side-effects left when component is unmounted.

It's a free world and you really don't have to use this component if it does not suit you =)

**Comment by nkbt** [comment]
Cheers 🍻

**Comment by waynebloss** [comment]
No, I was just saying that I would probably use it but after looking around for way too long about this subject in general and seeing sooo many simple examples, I just couldn't fathom what else was going on.

Thanks again!
